version: '3.8'

services:
  mercadolibre-ad-generator:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FLASK_DEBUG=True
    volumes:
      - ./output:/app/output
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    restart: unless-stopped
    container_name: mercadolibre-instagram-ad-generator

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - mercadolibre-ad-generator
  #   restart: unless-stopped
